[package]
name = "spitfire-glow"
version = "0.1.0"
edition = "2021"

[dependencies]
spitfire-core = { version = "0.1", path = "../../platform/core" }
bytemuck = { version = "1", features = ["derive"] }
