list:
    just --list

format:
    cargo fmt --all

remove-lockfiles:
    find . -name Cargo.lock -type f -exec rm {} +

build platform="desktop":
    just build-{{platform}}

build-web:
    wasm-pack build --target web

build-desktop:
    cargo build

run platform="desktop":
    just run-{{platform}}

run-desktop:
    cargo run

run-web:
    just build web
    http